### ISSUE TITLE
Update the reseller icon used in the WP dashboard

### ISSUE THREAD

**Issue by rramo012** [BoldGrid/library#14]
Update the reseller icon used in the dashboard to pull from remote so that it works for resellers without icon fonts saved in the plugin.

**Comment by timelsass** [comment]
resources/assets should be bundled in the library, and not distributed from remote sources -

1. not all installs are connected to a network, and this is a main UI component which should display regardless.

2. Plugins/themes are not allowed to do remote tracking without explicit user consent, a common way of doing this is pixel tracking, which could be applied in this same context.  From the WP Plugin guidelines, which says unrelated to a service:
"Offloading assets (including images and scripts) that are unrelated to a service."  

The unrelated to a service part is referring to it can be done if the feature is explicitly opt out when installed/activated, and the user explicitly agrees to allow sharing data and enabling tracking/usage.

Ultimately an icon in a dashboard is not really going to be seen as a software as a service, it provides no real functionality or additions to what the library does.

3. 3rd party remote execution is prohibited unless it's provided as SaaS functionality.   There is an exception to this, Fonts served over CDNs, but just remotely hosting a font so it can be updated with new resources is not the same thing as hosting versions over CDNs.  If the plugins/themes locked in a specific version that is pulled, and subsequent versions in the future pulled new versions hosted on our own CDN, then that would be acceptable.  This however is exactly the same as what we have bundled though as a user would have to upgrade their install to get the new version release per font.

-----

That said, it could maybe be something added into BoldGrid Inspirations, since this is not a .org hosted plugin, and already does remote code execution.  It also could possibly be it's own package which is included in premium plugins if the functionality is deemed necessary across all premium plugins.  Either way the library is used in free and premium plugins, so code that is added should comply with all aspects of free/premium in relation to plugin guidelines and theme guidelines.

**Comment by timelsass** [comment]
Please address the points above if you feel this ticket was inaccurately closed.
